In [2]:
import numpy as np

In [3]:
a=1,5,15,4454,154,554,154,5441,45454,411

In [4]:
b=np.mean(a)

In [5]:
b

5664.3

In [6]:
c=np.median(a)

In [7]:
c

282.5

In [11]:
np.max(a)

45454

In [12]:
arr2=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,1,2,3]])

In [15]:
arr3=np.array([[11,12,13,14],
               [15,16,17,18],
               [19,11,12,13]])

In [16]:
arr2+3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [17]:
arr3-arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [19]:
arr2/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [20]:
arr2*arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [21]:
arr2%4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)

In [22]:
arr2=np.array(arr2)

In [23]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [24]:
arr4=np.array([4,5,6,7])

In [25]:
arr2+arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [26]:
arr5=np.array([7,8])

In [28]:
arr5.shape

(2,)

In [32]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [41]:
arr1=np.array([[[1,2],
               [3,4],
               [5,6]],
             [[7,8],
              [9,10],
              [11,12]]])

In [42]:
arr1.shape


(2, 3, 2)

In [43]:
arr2=np.array([[5,6]])

In [44]:
arr1+arr2

array([[[ 6,  8],
        [ 8, 10],
        [10, 12]],

       [[12, 14],
        [14, 16],
        [16, 18]]])

In [3]:
arr1=np.array([[1,2,3],
               [3,4,5]])
arr2=np.array([[2,2,3],
               [1,2,5]])

In [4]:
arr1==arr2

array([[False,  True,  True],
       [False, False,  True]])

In [5]:
arr1!=arr2

array([[ True, False, False],
       [ True,  True, False]])

In [6]:
arr1>=arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [7]:
arr1<=arr2

array([[ True,  True,  True],
       [False, False,  True]])

In [8]:
arr1<arr2

array([[ True, False, False],
       [False, False, False]])

In [9]:
(arr1==arr2).sum()

3

In [10]:
np.sum(arr1==arr2)

3

In [11]:
arr3=np.array([
    [[11,12,13,14],
    [13,14,15,19]],
    
   [[15,16,17,21],
    [63,92,36,18]],
    
   [[98,32,81,23],
    [17,18,19.5,43]]
])

In [12]:
arr3[1,1,2]

36.0

In [15]:
arr3

array([[[11. , 12. , 13. , 14. ],
        [13. , 14. , 15. , 19. ]],

       [[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [14]:
arr3[1:,0:1,:22]

array([[[15., 16., 17., 21.]],

       [[98., 32., 81., 23.]]])

In [16]:
arr3[1:]

array([[[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [17]:
arr3[1:,0:1]

array([[[15., 16., 17., 21.]],

       [[98., 32., 81., 23.]]])

In [18]:
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [19]:
#all zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
#all ones 
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.random.rand(5,4,1)

array([[[0.64362302],
        [0.10474919],
        [0.33877058],
        [0.72808812]],

       [[0.10751437],
        [0.5682876 ],
        [0.69224868],
        [0.01473146]],

       [[0.12579957],
        [0.31107194],
        [0.46291302],
        [0.3225627 ]],

       [[0.10591118],
        [0.39715154],
        [0.79851122],
        [0.83548131]],

       [[0.9369589 ],
        [0.06877504],
        [0.8549326 ],
        [0.69610758]]])

In [24]:
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [26]:
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [31]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [32]:
np.linspace(3,27,9).reshape(3,3)

array([[ 3.,  6.,  9.],
       [12., 15., 18.],
       [21., 24., 27.]])